[package]
name = "platform"
version = "0.1.0"
edition = "2021"

[build-dependencies]
pkg-config = "0.3"

[dependencies]
xcb = "=0.9.0"
x11 = { version = "2.19", features = ["xlib"] }
libc = "0.2.171"
image = "0.25.6"
logger = { path = "../logger"}
